# SKILL VERSION: v25-skill (2026-07-21a)
# skills/stride-threat-model/scripts/concat-monolith.ps1
#
# Build artifact only. Concatenates the skill's reference files, in monolith
# phase order, into a single markdown file for diffing against the frozen
# v24 monolith or for human skimming. The skill files under references/ are
# the canonical, maintained source -- this script and its output are derived,
# not authoritative.
param(
  [string]$SkillDir = "$PSScriptRoot\..",
  [string]$OutFile = ".\stride-threat-model-concat.md"
)

$skillDir = $SkillDir.TrimEnd('\')
$refDir = "$skillDir\references"

$order = @(
  'common.md',
  'phase-0.md',
  'phase-1-shared.md',
  'phase-1a.md',
  'phase-1b.md',
  'phase-1c.md',
  'phase-1-reconcile.md',
  'phase-2a.md',
  'phase-2b.md',
  'phase-2c.md',
  'phase-3-dispositions.md',
  'phase-3-html.md',
  'phase-3-csv.md',
  'phase-4.md'
)

$header = "BUILD ARTIFACT -- generated by concat-monolith.ps1 from v25-skill; the skill files are canonical"

$parts = @($header, '')

foreach ($name in $order) {
    $path = "$refDir\$name"
    if (-not (Test-Path $path)) {
        throw "Missing reference file: $path"
    }
    $parts += "<!-- ===== $name ===== -->"
    $parts += (Get-Content $path -Raw).TrimEnd()
    $parts += ''
}

$content = ($parts -join "`n").TrimEnd() + "`n"
Set-Content -Path $OutFile -Value $content -Encoding UTF8 -NoNewline

$written = Get-Item $OutFile
$lineCount = @(Get-Content $OutFile).Count

"Wrote $OutFile"
"Size (bytes): $($written.Length)"
"Line count: $lineCount"
